- checkstyle.xml
- src/main/java/com/squareup/javawriter/builders/CodeWriter.java
- src/main/java/com/squareup/javawriter/builders/FieldSpec.java
- src/main/java/com/squareup/javawriter/builders/JavaFile.java
- src/main/java/com/squareup/javawriter/builders/MethodSpec.java
- src/main/java/com/squareup/javawriter/builders/Name.java
- src/main/java/com/squareup/javawriter/builders/ParameterSpec.java
- src/main/java/com/squareup/javawriter/builders/Snippet.java
- src/main/java/com/squareup/javawriter/builders/TypeSpec.java
- src/test/java/com/squareup/javawriter/builders/TypeSpecTest.java
This is currently in its own 'builders' subpackage. I'd like to get
more of this working, and then move it into the main 'javawriter'
package, and remove the code that's currently in that package.
> First, rough draft of immutable builders.

- src/main/java/com/squareup/javawriter/ParameterWriter.java
- src/test/java/com/squareup/javawriter/ParameterWriterTest.java
> Varargs support for parameters

- checkstyle.xml
- src/main/java/com/squareup/javawriter/ParameterizedTypeName.java
- src/main/java/com/squareup/javawriter/WildcardName.java
- src/main/java/com/squareup/javawriter/builders/AnnotationSpec.java
- src/main/java/com/squareup/javawriter/builders/CodeWriter.java
- src/main/java/com/squareup/javawriter/builders/FieldSpec.java
- src/main/java/com/squareup/javawriter/builders/MethodSpec.java
- src/main/java/com/squareup/javawriter/builders/Name.java
- src/main/java/com/squareup/javawriter/builders/ParameterSpec.java
- src/main/java/com/squareup/javawriter/builders/Snippet.java
- src/main/java/com/squareup/javawriter/builders/TypeSpec.java
- src/test/java/com/squareup/javawriter/builders/TypeSpecTest.java
Also improve modifiers, fields and annotations.
> Support anonymous inner classes in builders.

- src/test/java/com/squareup/javawriter/JavaFileTest.java
Closes https://github.com/square/javawriter/issues/80
> Test that the default package works.

- src/main/java/com/squareup/javawriter/ClassName.java
- src/main/java/com/squareup/javawriter/MethodSpec.java
- src/main/java/com/squareup/javawriter/ParameterSpec.java
- src/main/java/com/squareup/javawriter/Types.java
- src/test/java/com/squareup/javawriter/TypeSpecTest.java
Closes https://github.com/square/javawriter/issues/148
> Fix varargs for builders.

- src/main/java/com/squareup/javawriter/AnnotationSpec.java
- src/main/java/com/squareup/javawriter/CodeWriter.java
- src/main/java/com/squareup/javawriter/FieldSpec.java
- src/main/java/com/squareup/javawriter/JavaFile.java
- src/main/java/com/squareup/javawriter/JavaWriter.java
- src/main/java/com/squareup/javawriter/MethodSpec.java
- src/main/java/com/squareup/javawriter/ParameterSpec.java
- src/main/java/com/squareup/javawriter/TypeSpec.java
- src/main/java/com/squareup/javawriter/Types.java
- src/test/java/com/squareup/javawriter/JavaFileTest.java
Closes https://github.com/square/javawriter/issues/125
> Top of file comments. Stream to the filesystem.

- src/main/java/com/squareup/javapoet/CodeBlock.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
> Update CodeBlock documentation.

- src/main/java/com/squareup/javapoet/AnnotationSpec.java
- src/main/java/com/squareup/javapoet/CodeWriter.java
- src/main/java/com/squareup/javapoet/FieldSpec.java
- src/main/java/com/squareup/javapoet/JavaFile.java
- src/main/java/com/squareup/javapoet/MethodSpec.java
- src/main/java/com/squareup/javapoet/ParameterSpec.java
- src/main/java/com/squareup/javapoet/TypeSpec.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
Closes https://github.com/square/javapoet/issues/110
> Default modifiers.

- src/main/java/com/squareup/javapoet/MethodSpec.java
- src/main/java/com/squareup/javapoet/TypeSpec.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
Closes https://github.com/square/javapoet/issues/112
> Members ordering.

- src/main/java/com/squareup/javapoet/TypeSpec.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
Closes https://github.com/square/javapoet/issues/193
> Don't forbid abstract methods on enums.

- src/main/java/com/squareup/javapoet/CodeWriter.java
- src/main/java/com/squareup/javapoet/TypeSpec.java
- src/main/java/com/squareup/javapoet/Types.java
Will fail until rebase on #203.
> Add messages to state and argument validation.

- src/main/java/com/squareup/javapoet/ClassName.java
- src/main/java/com/squareup/javapoet/Util.java
- src/test/java/com/squareup/javapoet/ClassNameTest.java
Being non-ASCII isn't relevant.
> Character.isUpperCase follow up.

- src/main/java/com/squareup/javapoet/FieldSpec.java
- src/main/java/com/squareup/javapoet/MethodSpec.java
- src/main/java/com/squareup/javapoet/ParameterSpec.java
- src/main/java/com/squareup/javapoet/TypeSpec.java
- src/test/java/com/squareup/javapoet/FieldSpecTest.java
- src/test/java/com/squareup/javapoet/MethodSpecTest.java
- src/test/java/com/squareup/javapoet/ParameterSpecTest.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
Closes https://github.com/square/javapoet/issues/211
> Add Collection utilities on *Spec builders.

- pom.xml
> Switch to non-snapshot dependencies.

- src/main/java/com/squareup/javapoet/CodeBlock.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
Included a test using try-catch
> Fix nextControlFlow not accepting arguments

- src/main/java/com/squareup/javapoet/CodeBlock.java
- src/main/java/com/squareup/javapoet/CodeWriter.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
Closes: https://github.com/square/javapoet/issues/219
> Eager validation of argument types.

- src/main/java/com/squareup/javapoet/MethodSpec.java
- src/main/java/com/squareup/javapoet/TypeSpec.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
Adds a new Kind in TypeSpec to represent an annotation and adds an initializer in MethodSpec used to initialize methods of annotation type.
Closes #232
> Creates annotation type from TypeSpec.

- src/test/java/com/squareup/javapoet/TypeSpecTest.java
> Add test for simple if/else statement.

- src/main/java/com/squareup/javapoet/JavaFile.java
Nothing major, but probably a good idea.
> Add missing Override annotation

- src/main/java/com/squareup/javapoet/AnnotationSpec.java
- src/main/java/com/squareup/javapoet/CodeBlock.java
- src/main/java/com/squareup/javapoet/FieldSpec.java
- src/main/java/com/squareup/javapoet/JavaFile.java
- src/main/java/com/squareup/javapoet/MethodSpec.java
- src/main/java/com/squareup/javapoet/ParameterSpec.java
- src/main/java/com/squareup/javapoet/TypeSpec.java
> Add toBuilder() methods

- src/test/java/com/squareup/javapoet/FileWritingTest.java
> Force fake filesystem to behave like Unix.

- src/main/java/com/squareup/javapoet/CodeBlock.java
> Add missing $ in javadoc

- src/test/java/com/squareup/javapoet/FileReadingTest.java
Additional clean up for #276 (which has already been merged).
> Clean up FileReadingTest

- CHANGELOG.md
- src/main/java/com/squareup/javapoet/AnnotationSpec.java
- src/main/java/com/squareup/javapoet/FieldSpec.java
- src/main/java/com/squareup/javapoet/MethodSpec.java
- src/main/java/com/squareup/javapoet/ParameterSpec.java
- src/main/java/com/squareup/javapoet/TypeSpec.java
- src/main/java/com/squareup/javapoet/Util.java
- src/test/java/com/squareup/javapoet/AnnotationSpecTest.java
Change bulk operations to accept Iterable<T> rather than Collection<T>.
Style fixes.
> Small fixes for 1.1.0.

- src/main/java/com/squareup/javapoet/TypeName.java
- Initialize the ArrayList to some size.
- ~~Use array index lookup, instead of an interator.~~
I can squash the two separate commits, if you want.
> Minor changes to TypeName.list

- src/main/java/com/squareup/javapoet/TypeSpec.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
Closes https://github.com/square/javapoet/issues/291
> Javadoc on enum constants.

- src/test/java/com/squareup/javapoet/JavaFileTest.java
See https://github.com/square/wire/issues/184
See https://github.com/square/javapoet/issues/298
> Test conflicting simple names in the same file.

- README.md
> Use correct return type in inner class example

- src/main/java/com/squareup/javapoet/CodeBlock.java
- src/test/java/com/squareup/javapoet/CodeBlockTest.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
Fixes #309.
I'm not really sure about checking for unused arguments, it seems a little useless. If it is preferred, I'll write a test for it.
> Create better messages for auto-indexing

- src/main/java/com/squareup/javapoet/CodeBlock.java
- src/test/java/com/squareup/javapoet/CodeBlockTest.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
Pass the same tests with less code.
> Shorten parameter validation.

- src/test/java/com/squareup/javapoet/AbstractTypesTest.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
> Removed unused import statements.

- src/main/java/com/squareup/javapoet/CodeWriter.java
- src/test/java/com/squareup/javapoet/JavaFileTest.java
> Use qualified name for conflicting simple names in the same file

- src/main/java/com/squareup/javapoet/ArrayTypeName.java
- src/main/java/com/squareup/javapoet/TypeName.java
Great addition to the project, Eamonn.
> Removed not need import statements.

- src/main/java/com/squareup/javapoet/ClassName.java
Closes https://github.com/square/javapoet/issues/295
> Avoid Class.getPackage().

- src/main/java/com/squareup/javapoet/ClassName.java
- src/main/java/com/squareup/javapoet/CodeWriter.java
- src/main/java/com/squareup/javapoet/JavaFile.java
- src/test/java/com/squareup/javapoet/JavaFileTest.java
This introduces a new API that given a string, attempts to match it to
a class name. Then it uses that new API to discover the best name to
use when importing another type.
> Resolve-based import resolution.

- src/test/java/com/squareup/javapoet/TypeSpecTest.java
Pardon me, for re-creating the PR. Git troubles solved...
I removed the ```assumeTrue(isJava8());``` statement and used the STATIC enum member directly.
Btw. don't remove the other Java 8 related assumptions. ;-)
> Added test for static methods in an interface.

- src/main/java/com/squareup/javapoet/AnnotationSpec.java
- src/test/java/com/squareup/javapoet/AnnotationSpecTest.java
Here we go, again. Squashing squashed me, again.
Will add open inline comments below.
> AnnotationSpec.get(Annotation) added.

- src/main/java/com/squareup/javapoet/AnnotationSpec.java
- src/test/java/com/squareup/javapoet/AnnotationSpecTest.java
https://github.com/square/javapoet/issues/343
> Enum.name() usage forced

- src/main/java/com/squareup/javapoet/CodeWriter.java
Converting null to empty makes me uncomfortable. Just change the default
so we always have a package.
> Change around how we handle null package names.

- src/main/java/com/squareup/javapoet/AnnotatedTypeName.java
- src/main/java/com/squareup/javapoet/TypeName.java
- src/test/java/com/squareup/javapoet/TypeNameTest.java
> AnnotationTypeName added.

- src/main/java/com/squareup/javapoet/ArrayTypeName.java
- src/main/java/com/squareup/javapoet/ClassName.java
- src/main/java/com/squareup/javapoet/ParameterizedTypeName.java
- src/main/java/com/squareup/javapoet/TypeName.java
- src/main/java/com/squareup/javapoet/TypeVariableName.java
- src/main/java/com/squareup/javapoet/WildcardTypeName.java
- src/test/java/com/squareup/javapoet/AnnotatedTypeNameTest.java
> TypeName annotations added

- src/test/java/com/squareup/javapoet/JavaFileTest.java
Closes https://github.com/square/javapoet/issues/366
> Test to confirm nested annotation imports work.

- src/main/java/com/squareup/javapoet/AnnotationSpec.java
Better place, no public API change. This PR was part of #365
> Internal AnnotationSpec clean up.

- src/test/java/com/squareup/javapoet/TestFiler.java
Proposal for #391 - all tests remain green.
Is the internal "Source" class too simplistic? Am I missing something?
> Private source file object used, instead of com.sun.tools.javac types

- src/main/java/com/squareup/javapoet/AnnotationSpec.java
- src/test/java/com/squareup/javapoet/AnnotationSpecTest.java
Missing case `(value instanceof Character)` with test fix added.
> Added char/Character to AnnotationSpec.Builder.addValue logic

- src/main/java/com/squareup/javapoet/TypeSpec.java
> make TypeSpec.Kind enum public

- src/main/java/com/squareup/javapoet/ArrayTypeName.java
- src/main/java/com/squareup/javapoet/ClassName.java
- src/main/java/com/squareup/javapoet/ParameterizedTypeName.java
- src/main/java/com/squareup/javapoet/TypeName.java
- src/main/java/com/squareup/javapoet/WildcardTypeName.java
- src/test/java/com/squareup/javapoet/AnnotatedTypeNameTest.java
Follow up to @swankjesse's last comment on #417.
> Append annotations from multiple calls to TypeName#annotated

- src/main/java/com/squareup/javapoet/ArrayTypeName.java
- src/main/java/com/squareup/javapoet/ClassName.java
- src/main/java/com/squareup/javapoet/CodeWriter.java
- src/main/java/com/squareup/javapoet/ParameterizedTypeName.java
- src/main/java/com/squareup/javapoet/TypeName.java
- src/main/java/com/squareup/javapoet/TypeVariableName.java
- src/main/java/com/squareup/javapoet/WildcardTypeName.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
Closes: https://github.com/square/javapoet/issues/422
> Fix a bug where annotations broke import resolution.

- src/main/java/com/squareup/javapoet/TypeSpec.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
> Add TypeSpec factories for when a ClassName already exists.

- src/main/java/com/squareup/javapoet/AnnotationSpec.java
- src/main/java/com/squareup/javapoet/CodeBlock.java
- src/main/java/com/squareup/javapoet/CodeWriter.java
- src/main/java/com/squareup/javapoet/FieldSpec.java
- src/main/java/com/squareup/javapoet/MethodSpec.java
- src/test/java/com/squareup/javapoet/CodeBlockTest.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
> Revive CodeBlock.of()

- src/test/java/com/squareup/javapoet/JavaFileTest.java
- src/test/java/com/squareup/javapoet/TypeNameTest.java
> Removed dependency to compact2 types.

- src/test/java/com/squareup/javapoet/AnnotatedTypeNameTest.java
Added tests for https://github.com/square/javapoet/issues/431
> Two (ignored) tests for annotations on qualified names added

- src/main/java/com/squareup/javapoet/MethodSpec.java
- src/main/java/com/squareup/javapoet/Util.java
- src/test/java/com/squareup/javapoet/MethodSpecTest.java
> Ignore duplicate exceptions in MethodSpec.Builder

- src/main/java/com/squareup/javapoet/TypeVariableName.java
- src/test/java/com/squareup/javapoet/AbstractTypesTest.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
> TypeVariableName.withBounds added

- src/main/java/com/squareup/javapoet/TypeVariableName.java
> allow TypeName subclasses in withBounds() input list

- README.md
Tiny syntax fix according to the [test](https://github.com/sormuras/javapoet/blob/master/src/test/java/com/squareup/javapoet/JavaFileTest.java#L42).
> Added missing variable in import static example.

- src/main/java/com/squareup/javapoet/TypeSpec.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
> Allow fields in annotations

- src/main/java/com/squareup/javapoet/MethodSpec.java
- src/test/java/com/squareup/javapoet/MethodSpecTest.java
> Remove DEFAULT modifier from overridden method. #480

- src/main/java/com/squareup/javapoet/ClassName.java
- src/test/java/com/squareup/javapoet/ClassNameTest.java
> ClassName.reflectionName() added.

- src/main/java/com/squareup/javapoet/MethodSpec.java
Fixes #454 
Adds a method to add a single line comment to the code by adding to the format string.
> Add convenience method builder.addComment

- src/main/java/com/squareup/javapoet/TypeSpec.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
Addressing an oversight in #517.
> Disallow nulls in TypeSpec#addSuperinterfaces

- src/main/java/com/squareup/javapoet/TypeSpec.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
This adds a test and rolls back the changes made in a136eaa777b7750e16b3c6e8bd6d0228442e3e1d.
The tests contributed with that PR still pass.
> Fix imports of nested types.

- src/main/java/com/squareup/javapoet/TypeSpec.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
> Add convenience anonymousClassBuilder(CodeBlock)

- src/main/java/com/squareup/javapoet/CodeBlock.java
- src/main/java/com/squareup/javapoet/MethodSpec.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
Wasn't sure if this was the right place to add a test, but it didn't seem like CodeBlockTest of MethodSpecTest have tests for these types of things
> addStatement(CodeBlock) overloads for CodeBlock and MethodSpec

- src/main/java/com/squareup/javapoet/AnnotationSpec.java
- src/main/java/com/squareup/javapoet/CodeBlock.java
- src/main/java/com/squareup/javapoet/FieldSpec.java
- src/main/java/com/squareup/javapoet/MethodSpec.java
- src/main/java/com/squareup/javapoet/ParameterSpec.java
- src/main/java/com/squareup/javapoet/TypeSpec.java
The former has needless synchronization.
> Switch from StringWriter to StringBuilder.

- pom.xml
- src/test/java/com/squareup/javapoet/CodeBlockTest.java
- src/test/java/com/squareup/javapoet/FileReadingTest.java
- src/test/java/com/squareup/javapoet/MethodSpecTest.java
- src/test/java/com/squareup/javapoet/NameAllocatorTest.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
Replaced deprecated API calls with new ones.
> Updated various versions of 3rd-party libraries and tools

- pom.xml
- src/main/java/com/squareup/javapoet/CodeBlock.java
- src/test/java/com/squareup/javapoet/CodeBlockTest.java
Closes https://github.com/square/javapoet/issues/595
> Implement CodeBlock.join() and CodeBlock.joining()

- src/main/java/com/squareup/javapoet/CodeBlock.java
- src/test/java/com/squareup/javapoet/CodeBlockTest.java
> Add isEmpty to CodeBlock.Builder.

- src/test/java/com/squareup/javapoet/MethodSpecTest.java
and remove Mockito from MethodSpecTest.
> Add another test for direct generics usage.

- src/main/java/com/squareup/javapoet/ClassName.java
> Remove unused list

- README.md
Otherwise the result is always 0.
Closes #639.
> Initialize multiplication result to 1.

- src/main/java/com/squareup/javapoet/ClassName.java
- src/test/java/com/squareup/javapoet/AnnotatedTypeNameTest.java
I found the previous code difficult to follow. Hopefully this is less so.
> Tighten up the code that handles emitting type annotations.

- src/main/java/com/squareup/javapoet/ClassName.java
- src/test/java/com/squareup/javapoet/ClassNameTest.java
There's some bug that's triggered by Buck's ABI builds and avoiding this
API avoids triggering that bug.
> Avoid TypeElement.getKind() in ClassName.get().

- src/main/java/com/squareup/javapoet/TypeName.java
... but `java.util.List` does :)
> `java.lang.List` has no `size()` method

- src/main/java/com/squareup/javapoet/MethodSpec.java
- src/test/java/com/squareup/javapoet/MethodSpecTest.java
> Allow setting method name on MethodSpec.Builder

- pom.xml
Based on https://github.com/square/javapoet/network/alert/pom.xml/com.puppycrawl.tools:checkstyle/open
> Checkstyle 8.18

- src/main/java/com/squareup/javapoet/JavaFile.java
provide an easier using an encoding while writing a java file to a directory.
> easier_way_provide_encoding

- src/main/java/com/squareup/javapoet/CodeBlock.java
- src/test/java/com/squareup/javapoet/CodeBlockTest.java
Analogous to the change added in KotlinPoet
> Add CodeBlock.Builder#clear() method

- src/main/java/com/squareup/javapoet/TypeSpec.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
> Copy originating elements in toBuilder() as well

- src/main/java/com/squareup/javapoet/MethodSpec.java
- src/test/java/com/squareup/javapoet/MethodSpecTest.java
Convenience overloads to use CodeBlocks in control flows. This useful when working with named code and some special cases.
Fixes #751
> added convenience overloads for code blocks in control flow

- src/main/java/com/squareup/javapoet/TypeSpec.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
Closes #805 
Since Java 9 interface methods can be private
> Allow private Interface methods

- src/main/java/com/squareup/javapoet/TypeSpec.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
Adds support for enums without constants.
> Support enums without any enum constants

- pom.xml
https://mvnrepository.com/artifact/com.google.testing.compile/compile-testing
> compile-testing 0.19

- pom.xml
https://github.com/mockito/mockito/releases/tag/v4.4.0
﻿
> mockito 4.4.0
