square/javapoet

- src/main/java/com/squareup/javawriter/ClassName.java
- src/main/java/com/squareup/javawriter/TypeVariableName.java
- src/main/java/com/squareup/javawriter/builders/CodeWriter.java
- src/main/java/com/squareup/javawriter/builders/MethodSpec.java
- src/main/java/com/squareup/javawriter/builders/TypeSpec.java
- src/test/java/com/squareup/javawriter/builders/TypeSpecTest.java
```
TypeVariables are tricky because in the declaration we write it as
<T extends CharSequence> but everywhere else it's just <T>.
```
> Type variables, implements and extends.

- src/main/java/com/squareup/javawriter/ClassName.java
- src/main/java/com/squareup/javawriter/builders/CodeWriter.java
- src/main/java/com/squareup/javawriter/builders/FieldSpec.java
- src/main/java/com/squareup/javawriter/builders/JavaFile.java
- src/main/java/com/squareup/javawriter/builders/MethodSpec.java
- src/main/java/com/squareup/javawriter/builders/TypeSpec.java
- src/test/java/com/squareup/javawriter/builders/JavaFileTest.java
- src/test/java/com/squareup/javawriter/builders/TypeSpecTest.java
This changes TypeSpec to no longer know what its enclosing package,
and potentially also not its enclosing class if there was one. This
makes TypeSpec work the same as FieldSpec and MethodSpec, which also
don't know how they are enclosed. As a model I think it's simpler,
particularly since it was often a lie anyway: what is the fully qualified
name of an anonymous class?
This also improves imports for nested classes.
> Nested classes and imports.

- src/main/java/com/squareup/javapoet/AnnotationSpec.java
- src/main/java/com/squareup/javapoet/ClassName.java
- src/main/java/com/squareup/javapoet/CodeBlock.java
- src/main/java/com/squareup/javapoet/CodeWriter.java
- src/main/java/com/squareup/javapoet/FieldSpec.java
- src/main/java/com/squareup/javapoet/JavaFile.java
- src/main/java/com/squareup/javapoet/JavaPoet.java
- src/main/java/com/squareup/javapoet/MethodSpec.java
- src/main/java/com/squareup/javapoet/ParameterSpec.java
- src/main/java/com/squareup/javapoet/TypeSpec.java
- src/test/java/com/squareup/javapoet/ClassNameTest.java
- src/test/java/com/squareup/javapoet/JavaFileTest.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
Drop a convenience overload for addParameter that was inconsistent;
we don't have similar shortcuts for fields.
Also restore peerNamed() needed by Dagger 2.
> API ergonomics redux.

- src/main/java/com/squareup/javapoet/MethodSpec.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
Stop generating curly braces for native methods and allow arbritary code before the semi-colon to support stuff like GWT JSNI.
I also moved code for abstract method to support exceptions.
It fixes issue #190.
> Native methods and GWT JSNI

- src/main/java/com/squareup/javapoet/CodeBlock.java
- src/main/java/com/squareup/javapoet/CodeWriter.java
- src/main/java/com/squareup/javapoet/JavaPoet.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
We had a bug when using Filer to emit to the default package.
Don't wrap null in quotes when emitting it as a string.
> Small features for Dagger.

- src/main/java/com/squareup/javapoet/CodeWriter.java
- src/main/java/com/squareup/javapoet/JavaFile.java
- src/main/java/com/squareup/javapoet/JavaPoet.java
- src/main/java/com/squareup/javapoet/Types.java
- src/test/java/com/squareup/javapoet/JavaFileTest.java
- src/test/java/com/squareup/javapoet/JavaPoetTest.java
Hi,
I have added configurable indent. It solves issue #106 . Indent can be configured in `JavaPoet` class (old `JavaWriter` class). Exemplary usage of the configurable indent is presented in the following code snippet:
```java
new JavaPoet(new Indent().level(4));
```
In addition, I've added appropriate Unit Tests verifying behavior of the library with new functionality.
I wanted to make code clean and as abstract as possible.
I hope it would be useful for you.
Regards,
Piotr
> adding configurable indent

- src/main/java/com/squareup/javapoet/FieldSpec.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
The FieldSpec initializer may be called 0 or 1 times. Previousy,
it could be called multiple times to create a multi-line statement.
As the method name initializer implies a single statement per call,
a CodeBlock may be provided for complex initialization scenarios.
> Don't allow double field initialization.

- src/test/java/com/squareup/javapoet/ClassNameTest.java
- src/test/java/com/squareup/javapoet/FileWritingTest.java
- src/test/java/com/squareup/javapoet/JavaFileTest.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
- src/test/java/com/squareup/javapoet/TypesTest.java
Add @RunWith boilerplate to tests - lets alternative test runners in other build systems pick the correct runner.
> Add @RunWith boilerplate to tests

- src/main/java/com/squareup/javapoet/WildcardTypeName.java
- src/test/java/com/squareup/javapoet/TypesTest.java
It would always fail with NulllPointerException since either the extends bound or the super bound or both will be null.
> Fix WildcardTypeName.get(WildcardType)

- src/main/java/com/squareup/javapoet/CodeBlock.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
It should include a space before {. Bizarrely, a test checks the current behaviour, but I don't see how it can be desirable.
> Change CodeBlock.nextControlFlow to be consistent with beginControlFlow.

- src/main/java/com/squareup/javapoet/MethodSpec.java
- src/test/java/com/squareup/javapoet/MethodSpecTest.java
Anyone know a good way to test this without writing a novel of mocking? I filed https://github.com/google/compile-testing/issues/65 which seems like it would be a good approach.
Closes #228.
> MethodSpec factory for overriding an ExecutableElement.

- src/main/java/com/squareup/javapoet/TypeSpec.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
This is a simple check to avoid duplicate settings and primitive
types. This does not assert that the parameter is set to
`ClassName.OBJECT` twice, as that seemed to be an unnecessary
complication.
> Add precondition check when specifying the superclass

- src/main/java/com/squareup/javapoet/TypeSpec.java
- src/main/java/com/squareup/javapoet/Util.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
Adds support for most Java 8 modifier changes.
> Add support for Java 8 modifier changes

- src/main/java/com/squareup/javapoet/CodeWriter.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
When a type in the current package has the same name as a type in another package, javapoet should not attempt to import the other package's type; rather, it should just refer to it by its fully qualified name.
> Fix import error.

- src/main/java/com/squareup/javapoet/Util.java
Array printing without `Arrays.toString` isn't pretty.
> Fix Util error message

- src/main/java/com/squareup/javapoet/ClassName.java
Class.getPackage() might return null, and does for Proxy instances.
Better guard .getName() with null-check.
> Prevent potential NPE when getting package reference.

- src/main/java/com/squareup/javapoet/AnnotationSpec.java
- src/test/java/com/squareup/javapoet/AnnotationSpecTest.java
Added static get method to AnnotationSpec using an AnnotationMirror as source.
Next, I implemented some of the TODOs in MethodSpec.overriding - and changed the signature to include an ExecutableType. That allows the actual generic type parameters retrieval for the return type and the signature.
See the interface extending parameterized interfaces test case: ExtendsOthers in MethodSpecTest.
PS: This time, checkstyle and unit tests are green: https://travis-ci.org/sormuras/javapoet
> AnnotationSpec.get and MethodSpec.overriding

- src/main/java/com/squareup/javapoet/JavaFile.java
- src/test/java/com/squareup/javapoet/FileReadingTest.java
As discussed in #267, adds a helper to simplify passing a `JavaFile` to a `javax.tools.JavaCompiler`.
> JavaFile.toJavaFileObject

- src/main/java/com/squareup/javapoet/AnnotationSpec.java
- src/test/java/com/squareup/javapoet/AnnotationSpecTest.java
AnnotationSpec.toBuilder() did return an immutable collection.
AnnotationSpec.get(AnnotationMirror) visitor now visits arrays as well.
> AnnotationSpec fixes

- src/main/java/com/squareup/javapoet/MethodSpec.java
First, the PR contains a minor update of the varargs()-method in the MethodSpec.Builder:
* added method varargs(boolean varargs) which allows a) setting the value to false and b) cleaner code in API usage, i.e. `builder.varargs(method.isVarArgs())` instead of
```java
if (method.isVarArgs()) {
builder.varargs();
}
```
* second, the `boolean chainable` is introduced. It indicates a assignable type relation between the method container and the method return type. Usually, it means, the method returns `this`. That relation is difficult to reflect after the MethodSpec is built. It is easier to obtain, when the annotation process is running and providing Types utilities:
```java
boolean chainable = processingEnv.getTypeUtils().isAssignable(declaringType, method.getReturnType());
```
Knowing …
> MethodSpec.varargs(boolean) added

- README.md
- src/main/java/com/squareup/javapoet/MethodSpec.java
- src/test/java/com/squareup/javapoet/MethodSpecTest.java
Hi JavaPoets,
before rebasing https://github.com/square/javapoet/pull/281 I created this simpler PR that concentrates only on the `overriding` implementation without introducing package private classes.
> Overriding-only w/o poet support

- src/main/java/com/squareup/javapoet/CodeBlock.java
- src/test/java/com/squareup/javapoet/CodeBlockTest.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
In response to issue #238 I added in the ability to use indexes in the format strings.
I used the $-index-format syntax discussed in that thread and made the index start at one to be consistent with the way that java formatters act.
> Added the ability to use indexes in format arguments

- src/main/java/com/squareup/javapoet/MethodSpec.java
- src/main/java/com/squareup/javapoet/ParameterSpec.java
- src/test/java/com/squareup/javapoet/MethodSpecTest.java
Also rearrange the type resolution version of that method so the
simple case doesn't need a Types class.
> Restore the deleted MethodSpec.overriding() overload.

- pom.xml
- src/main/java/com/squareup/javapoet/TypeVariableName.java
- src/test/java/com/squareup/javapoet/AbstractTypesTest.java
- src/test/java/com/squareup/javapoet/TypesEclipseTest.java
- src/test/java/com/squareup/javapoet/TypesTest.java
When in presence of a TypeVariable with an intersection type as the upper
bound, Eclipse JDT/APT returns a TypeVariable equivalent to the declaring
TypeVariable when calling getUpperBound. The only way to retrieve the
actual bounds is to go look at the TypeParameterElement represented by
the TypeVariable.
See #303
> Workaround for Eclipse JDT/APT bug around intersection types

- src/main/java/com/squareup/javapoet/TypeSpec.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
Per issue [253](https://github.com/square/javapoet/issues/253), this change relaxes the prohibition on annotations for anonymous classes and adds the annotation  to the emitter.
> Issue 253 - Added support for annotations on enum values

- src/main/java/com/squareup/javapoet/NameAllocator.java
- src/test/java/com/squareup/javapoet/NameAllocatorTest.java
Useful to refine a NameAllocator for use in an inner scope code block.
> Add clone() method on NameAllocator

- src/main/java/com/squareup/javapoet/AnnotationSpec.java
- src/main/java/com/squareup/javapoet/CodeBlock.java
- src/main/java/com/squareup/javapoet/CodeWriter.java
- src/main/java/com/squareup/javapoet/FieldSpec.java
- src/main/java/com/squareup/javapoet/JavaFile.java
- src/main/java/com/squareup/javapoet/MethodSpec.java
- src/main/java/com/squareup/javapoet/ParameterSpec.java
- src/main/java/com/squareup/javapoet/TypeName.java
- src/main/java/com/squareup/javapoet/TypeSpec.java
- src/test/java/com/squareup/javapoet/AnnotationSpecTest.java
- src/test/java/com/squareup/javapoet/CodeBlockTest.java
- src/test/java/com/squareup/javapoet/FieldSpecTest.java
- src/test/java/com/squareup/javapoet/MethodSpecTest.java
- src/test/java/com/squareup/javapoet/ParameterSpecTest.java
- src/test/java/com/squareup/javapoet/TypeNameTest.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
https://github.com/square/javapoet/issues/345
Take 2
If a common base class for all Specs, Names and CodeBlock is too intrusive/restrictive, I'll unroll the two methods into all types extending Base.
> equals() and hashCode() implemented.

- src/main/java/com/squareup/javapoet/ArrayTypeName.java
- src/main/java/com/squareup/javapoet/ParameterizedTypeName.java
- src/main/java/com/squareup/javapoet/TypeName.java
- src/main/java/com/squareup/javapoet/TypeVariableName.java
- src/main/java/com/squareup/javapoet/WildcardTypeName.java
- src/test/java/com/squareup/javapoet/TypeNameTest.java
Fixes #356 analog to the `TypeName.get(TypeMirror)` fix by Eamonn.
See https://github.com/square/javapoet/commit/6551850b3eaa4f5ff4b6ce6a2b2102d281a11fee
> StackOverflowError fixed.

- src/main/java/com/squareup/javapoet/CodeWriter.java
- src/test/java/com/squareup/javapoet/JavaFileTest.java
A possible solution for #369 - don't put empty class names with empty package names into the `importableTypes` map.
> Prevent import of types located in the default package. 

- src/main/java/com/squareup/javapoet/CodeBlock.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
Fix for #329 -- even though String.format() does really not complain unused indexed arguments.
> Unused indexed arguments do fail now.

- src/main/java/com/squareup/javapoet/ArrayTypeName.java
- src/main/java/com/squareup/javapoet/ClassName.java
- src/main/java/com/squareup/javapoet/ParameterizedTypeName.java
- src/main/java/com/squareup/javapoet/TypeName.java
- src/main/java/com/squareup/javapoet/TypeVariableName.java
- src/main/java/com/squareup/javapoet/WildcardTypeName.java
Made `TypeName#annotated(AnnotationSpec... annotations)` final and use the `List<AnnotationSpec>` variant.
Removed all unnecessary overridden methods from various TypeName subclasses.
> TypeName#annotated clean up

- checkstyle.xml
- pom.xml
- src/main/java/com/squareup/javapoet/CodeWriter.java
- src/main/java/com/squareup/javapoet/TypeSpec.java
* Removed redundant modifiers in CodeWriter and TypeSpec
* Module RedundantThrows commented out - it was removed from CS
* Java 8 method reference syntax parsing fixed
> Upgrade Maven Checkstyle Plugin to 2.17 using Checkstyle 6.11.2

- src/main/java/com/squareup/javapoet/AnnotationSpec.java
- src/main/java/com/squareup/javapoet/CodeWriter.java
- src/test/java/com/squareup/javapoet/AnnotationSpecTest.java
Fixes #395 if the value is a single ``'`` character.
> Escape special char values.

- src/main/java/com/squareup/javapoet/CodeWriter.java
- src/main/java/com/squareup/javapoet/JavaFile.java
- src/main/java/com/squareup/javapoet/ParameterizedTypeName.java
- src/main/java/com/squareup/javapoet/TypeName.java
- src/main/java/com/squareup/javapoet/TypeVariableName.java
- src/main/java/com/squareup/javapoet/WildcardTypeName.java
- src/test/java/com/squareup/javapoet/JavaFileTest.java
Solves #73 like @swankjesse wants it. :sweat_smile:
Also includes a fix for a stack overflow that happend inside/between `hashCode()`s of `ParameterizedTypeName` and `TypeVariableName`.
> Static import support added.

- CHANGELOG.md
- README.md
- src/main/java/com/squareup/javapoet/CodeWriter.java
- src/test/java/com/squareup/javapoet/JavaFileTest.java
@swankjesse wrote in #398 
> I suspect there’s a few unlikely corner cases, such as when the last format part is a $T, but this is certainly better than what we have now. I might take a pass at this code to get rid of the nasty word glean and to try to tighten up those exotic & unlikely cases.
* Is `extractMemberName` better?
* Fix and test for the "one character member name" like `$T.X` is included.
* More exotic cases are tested. Which are missing?
* Does [wire](https://github.com/square/wire) work with current SNAPSHOT of JavaPoet?
>  I’m also tempted to try to make this work with $L, so you don’t need to statically know what you’re statically importing!
Sounds like a brave plan. You mean like having `$T.$L` resolve to `.addStaticImport($T, $L)` ? Same with `$T.$N`?
> Static import corner case tests.

- src/main/java/com/squareup/javapoet/ArrayTypeName.java
- src/main/java/com/squareup/javapoet/ClassName.java
- src/main/java/com/squareup/javapoet/ParameterizedTypeName.java
- src/main/java/com/squareup/javapoet/TypeName.java
- src/main/java/com/squareup/javapoet/TypeVariableName.java
- src/main/java/com/squareup/javapoet/WildcardTypeName.java
- src/test/java/com/squareup/javapoet/AnnotatedTypeNameTest.java
Made TypeName.equals() and TypeName.hashCode() final and respect attached annotations by using toString() representation. Removed all overridings in derived classes.
Fixes #400
> TypeName.equals() and .hashCode() now respect attached annotations.

- src/main/java/com/squareup/javapoet/AnnotationSpec.java
- src/main/java/com/squareup/javapoet/CodeWriter.java
- src/main/java/com/squareup/javapoet/Util.java
- src/test/java/com/squareup/javapoet/AnnotationSpecTest.java
- src/test/java/com/squareup/javapoet/UtilTest.java
`Character` and `String` literal conversion refactored.
Made `AnnotationSpec.Builder.addMemberForValue(String format, Object value)` public.
Removed redundant public modifiers from package private Util methods.
Added `UtilTest` class.
> Literal conversion clean up.

- src/main/java/com/squareup/javapoet/ArrayTypeName.java
- src/main/java/com/squareup/javapoet/ClassName.java
- src/main/java/com/squareup/javapoet/ParameterizedTypeName.java
- src/main/java/com/squareup/javapoet/TypeName.java
- src/main/java/com/squareup/javapoet/WildcardTypeName.java
- src/test/java/com/squareup/javapoet/AnnotatedTypeNameTest.java
I don't love that this requires each `TypeName` subclass needs to remember to combine the old and new annotations, but I don't see a good way to enforce that since `TypeName#annotated(List<AnnotationSpec>)` needs to be overridable to be able to return the right type. Open to suggestions.
One of the tests assumed that calling `annotatedTypeName.annotated()` would clear this test - I'm not sure if anyone relies on that functionality, but that would be a breaking change. I could add a `clearAnnotations()` method if you'd like.
> Allow TypeNames to be annotated twice

- src/main/java/com/squareup/javapoet/TypeSpec.java
Other modifiers like static are not allowed for annotation
methods.
The exception message no longer suggests that
annotation methods cannot have modifiers, which is misleading
since public and abstract is in fact required.
> Annotation methods to be public, abstract and nothing else

- pom.xml
I couldn't build the head of JavaPoet with truth 1.0-SNAPSHOT and compile-testing 1.0-SNAPSHOT.
> fix dependency versions to test

- src/main/java/com/squareup/javapoet/TypeSpec.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
Fixed the name clash that arises in this instance (https://github.com/square/javapoet/issues/470):
TypeSpec ts = TypeSpec.interfaceBuilder("Example")
.addSuperInterface(ClassName.get("org.pack", "Example")).build();
System.out.println(JavaFile.Builder("com.ex", ts).build().toString());
Which prints the non-compiling:
package com.ex;
import org.pack.Example;
interface Example extends Example {
}
It now qualifies org.pack.Example properly:
`interface Example extends org.pack.Example {`
> Fixed the name clash when implementing/extending classes

- src/main/java/com/squareup/javapoet/TypeSpec.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
`superclass` needs `Kind.CLASS`
Closes #502.
> Check kind state when adding super class. #502

- src/main/java/com/squareup/javapoet/TypeSpec.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
If `null` makes it in, we encounter obscure stacktraces later when emitting, such as this one:
```
java.lang.IllegalArgumentException: expected type but was null
at com.squareup.javapoet.CodeBlock$Builder.argToType(CodeBlock.java:207)
at com.squareup.javapoet.CodeBlock$Builder.add(CodeBlock.java:170)
at com.squareup.javapoet.CodeWriter.emit(CodeWriter.java:196)
at com.squareup.javapoet.TypeSpec.emit(TypeSpec.java:178)
```
> Guard for null in TypeSpec.Builder#addSuperinterface(TypeName)

- src/main/java/com/squareup/javapoet/JavaFile.java
- src/main/java/com/squareup/javapoet/Util.java
- src/test/java/com/squareup/javapoet/FileReadingTest.java
- src/test/java/com/squareup/javapoet/FileWritingTest.java
Sometimes the system default charset is not UTF-8 and this is sad.
We always want UTF-8, and we want to encourage anyone doing tools
to use UTF-8.
Closes: https://github.com/square/javapoet/pull/474
> Always write UTF-8.

- src/main/java/com/squareup/javapoet/CodeBlock.java
- src/main/java/com/squareup/javapoet/CodeWriter.java
- src/main/java/com/squareup/javapoet/LineWrapper.java
- src/main/java/com/squareup/javapoet/MethodSpec.java
- src/test/java/com/squareup/javapoet/CodeBlockTest.java
- src/test/java/com/squareup/javapoet/LineWrapperTest.java
- src/test/java/com/squareup/javapoet/MethodSpecTest.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
Currently only method parameters are wrapped. Anything else can be wrapped
by replacing a space with $W.
https://github.com/square/javapoet/issues/105
> Implement line wrapping.

- src/main/java/com/squareup/javapoet/AnnotationSpec.java
- src/main/java/com/squareup/javapoet/ParameterSpec.java
- src/test/java/com/squareup/javapoet/MethodSpecTest.java
We recently merged this because it was demanded, but looking through our
history we've had vocal users complaining about this exact kind of
behavior.
https://github.com/square/javapoet/pull/487/files
> Rollback support for retaining parameter annotations.

- README.md
- src/test/java/com/squareup/javapoet/JavaFileTest.java
There is a missing symbol "?" in [$T for Types] - [Import static]
> There is a missing symbol "?" in [$T for Types] - [Import static]

- src/test/java/com/squareup/javapoet/TypeNameTest.java
Hello,
I open this pull request to specify the line [197](https://github.com/square/javapoet/blob/master/src/main/java/com/squareup/javapoet/TypeName.java#L197) in the ```equals()``` method of ```com.squareup.javapoet.TypeName```.
```java
if (o == null) return false;
```
> Improve test on TypeName

- src/main/java/com/squareup/javapoet/MethodSpec.java
- src/test/java/com/squareup/javapoet/MethodSpecTest.java
I encountered the NPEs because of variations in the API response which I use to generate my code. I figured it would be better to add some messaging to the NPEs, rather that getting the vanilla NPEs.
> Adds messaging to NPEs thrown in MethodSpec.methodBuilder(),addModifiers()

- src/main/java/com/squareup/javapoet/TypeSpec.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
Encountered unexpected behaviour when printing a class as the result of a null being passed from the result of a method call into `TypeSpec` modifiers
> Verify that null is not passed as vararg parameter

- src/main/java/com/squareup/javapoet/ClassName.java
- src/test/java/com/squareup/javapoet/ClassNameTest.java
ClassName#get incorrectly used Class#getSimpleName for anonymous inner classes, which is an empty string.
With this change it falls back to using Class#getName for anonymous classes and taking the compiler generated name for the class.
`mvn clean verify` passed, signed the CLA.
> Support anonymous inner classes in ClassName#get

- src/main/java/com/squareup/javapoet/ClassName.java
- src/test/java/com/squareup/javapoet/ClassNameTest.java
Fixes a regression introduced in #526 where classes whose names start with a `$`would incorrectly have `.` separators removed - for example, a class `$Bar` in package `foo` would be named `foo$Bar` rather than the expected `foo.$Bar`.
This is only really a problem when generated code references other generated code, but I imagine that's fairly common for consumers of this library.
> Fix ClassName regression for class names starting with a $

- src/main/java/com/squareup/javapoet/CodeWriter.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
Turns out this was already covered in a test but we had the wrong expected output declared.
Closes #573.
> Include annotations when emitting type variables.

- pom.xml
Claim `com.squareup.javapoet` as Automatic-Module-Name in the JAR MANIFEST.
The name matches the java package name in which all compilation units reside. It does not match the github "user" name `square`.
See http://branchandbound.net/blog/java/2017/12/automatic-module-name/ for details and background.
Closes #589
> Set com.squareup.javapoet as automatic module name

- src/main/java/com/squareup/javapoet/CodeBlock.java
- src/main/java/com/squareup/javapoet/CodeWriter.java
- src/main/java/com/squareup/javapoet/LineWrapper.java
- src/test/java/com/squareup/javapoet/CodeBlockTest.java
- src/test/java/com/squareup/javapoet/LineWrapperTest.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
Closes https://github.com/square/javapoet/issues/588
I left a few comments in the code with questions that I had.
As I was implementing it, I was thinking that `$Z` may make more sense (`$W` is for _whitespace, `$Z` is for zero-whitespace?). But it's late, so maybe I'm thinking sideways.
I didn't love the `FlushType`/`nextFlush` names. Open to other suggestions (again, it was late, so `FlushType` made tons of sense to me)
> Adds `$B` as an optional newline if a line will exceed 100 chars

- pom.xml
- src/main/java/com/squareup/javapoet/LineWrapper.java
- src/main/java/com/squareup/javapoet/MethodSpec.java
- src/test/java/com/squareup/javapoet/MethodSpecTest.java
Now we wrap automatically after the method name, if appropriate.
> Use $Z in method parameter lists.

- src/main/java/com/squareup/javapoet/CodeWriter.java
I was scanning through this file and this error message seemed wrong to me. If the checkState fails, the packageName _not_ be set, right?
> Fix checkState message in CodeWriter

- .buildscript/install-jdk.sh
- .travis.yml
Just to make sure JavaPoet builds on various JDKs.
There's a warning printed on all JDK >= 9:
```
[...]
Running com.squareup.javapoet.TypesEclipseTest
Annotation processing got disabled, since it requires a 1.6 compliant JVM
[...]
Tests run: 317, Failures: 0, Errors: 0, Skipped: 4
```
But no test fails?! Same test run numbers a generated by JDK 8.
> Introduce JDK build matrix on Travis CI

- README.md
Should have return type of `String`, not `void`.
> Correct usage of toString() in readme

- src/main/java/com/squareup/javapoet/TypeSpec.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
`fun getGeneratedAnnotation() : AnnotationSpec?`
`addAnnotation(getGeneratedAnnotation())` wouldn't fail until the type was emitted.
(If these low-effort PRs aren't worth anything, feel free to let me know and close, of course.)
> Fail fast with null AnnotationSpec on type.

- pom.xml
Use latest `errorprone` version, which seems to be Java 11-ready.
> Upgrade errorprone to 2.3.1

- .travis.yml
- pom.xml
As https://github.com/travis-ci/travis-build/pull/1347 was merged, Travis supports `jdk: openjdk..` synatx again.
Left out `openjdk9` as it reached EOL some months ago.
> Switch back to Travis CI managed "jdk" installations

- src/main/java/com/squareup/javapoet/CodeWriter.java
- src/main/java/com/squareup/javapoet/MethodSpec.java
- src/main/java/com/squareup/javapoet/TypeSpec.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
Originally reported here: https://github.com/google/dagger/issues/1230
Type variables technically have preference even over types in the same package, so if one exists with the same name, we should ignore any package information.
> Qualify types masked by type variables

- src/test/java/com/squareup/javapoet/NameAllocatorTest.java
In case of a refactoring, one could introduce a regression on the [conditional](https://github.com/square/javapoet/blob/master/src/main/java/com/squareup/javapoet/NameAllocator.java#L132).
For example, if one changes  `==` by `>=`, the current test suite passes, while the proposed improvement doesn't.
> test: specify more toJavaIdentifier

- src/main/java/com/squareup/javapoet/MethodSpec.java
- src/main/java/com/squareup/javapoet/ParameterSpec.java
- src/test/java/com/squareup/javapoet/MethodSpecTest.java
Resolves #495 
Wanted to get some feedback. Right now, to ensure that the `@param name description of name` comes to the end of the Javadoc, I've kept a separate field called `parameterJavadoc`. I'm unsure whether that is the best practice since if we think about adding Javadoc to return types and exception, it might be a bit much. 
The alternative is to put the onus on the consumer to then do:
```java
methodSpec
.addJavadoc("Method description")
.addParameter(ParameterSpec.builder(String.class, "name")
.addJavadoc("The name of the user\n")
.build())
```
and make sure that the method javadoc comes before the parameter javadoc.
> Add Javadoc to ParameterSpec

- src/main/java/com/squareup/javapoet/ClassName.java
- src/test/java/com/squareup/javapoet/ClassNameTest.java
Canonical name may be useful when creating `JavaFileObject` for code generation in APT Processor instead of manually concatenating `packageName()` and `simpleName()`
> Public getter for canonical name of ClassName

- src/main/java/com/squareup/javapoet/CodeWriter.java
- src/main/java/com/squareup/javapoet/TypeSpec.java
For one large (100K lines) Dagger component implementation, this saved 3.5s/build. The type has ~360 subcomponents, and each of those have a sibling builder type, so ~720 nested types at the worst point. 
I wasn't sure what your style preferences are for whether `nestedTypesSimpleNames` should be immutable or not given that it's internal, so I implemented it as mutable and figured I'd ask your thoughts. I can also call `Util.immutableSet()` or create a single mutable set that never escaped and wrap that in an `unmodifiableSet`.
> Remove n^2 algorithm in CodeWriter.resolve() by precomputing all of the nested simple names of a TypeSpec

- src/main/java/com/squareup/javapoet/CodeBlock.java
The single-argument overload will use the end of the String as the end index automatically.
> Remove argument whose value isn't needed

- src/main/java/com/squareup/javapoet/ClassName.java
In addition to being used repeatedly in CodeWriter.lookupName(), the current implementation is N^2 (albeit for a usually low N) since it recursively calls itself on the enclosing class name. This should get rid of some of the garbage created in code writing.
> Memoize ClassName.simpleNames()

- src/main/java/com/squareup/javapoet/TypeSpec.java
I created an ErrorProne refactoring to detect superfluous `CodeBlock.Builder` usages. Conveniently, I found one in JavaPoet itself :)
> Nit: Simplify a CodeBlock

- .buildscript/deploy_snapshot.sh
- .travis.yml
This should hopefully resolve CI issues on PRs since oraclejdk8 isn't available without the trusty dist anymore
> Switch to openjdk8 for CI

- src/main/java/com/squareup/javapoet/ParameterSpec.java
- src/test/java/com/squareup/javapoet/MethodSpecTest.java
- src/test/java/com/squareup/javapoet/ParameterSpecTest.java
- src/test/java/com/squareup/javapoet/TestUtil.java
Resolves #665 
I'd love to add some tests around the `get(variableElement)` method but I'm not sure how to do that with creating a `VariableElement`. If you have any suggestions, let me know!
> Add checks to ParameterSpec with VariableElement + copy over annotations

- src/main/java/com/squareup/javapoet/AnnotationSpec.java
- src/main/java/com/squareup/javapoet/FieldSpec.java
- src/main/java/com/squareup/javapoet/JavaFile.java
- src/main/java/com/squareup/javapoet/MethodSpec.java
- src/main/java/com/squareup/javapoet/ParameterSpec.java
- src/main/java/com/squareup/javapoet/TypeSpec.java
- src/test/java/com/squareup/javapoet/AnnotationSpecTest.java
- src/test/java/com/squareup/javapoet/FieldSpecTest.java
- src/test/java/com/squareup/javapoet/JavaFileTest.java
- src/test/java/com/squareup/javapoet/MethodSpecTest.java
- src/test/java/com/squareup/javapoet/ParameterSpecTest.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
A case that often comes up for us is that if you expose a post processing API in code gen, builders become a pain because any list property in a builder is append-only. 
What this means is that in order to modify one of them, you have to manually make a new copy of the type that builder is constructing and copy over every property but the one you're trying to change. Then for the one you're changing, you have to copy all the other ones and then your modified version.
A classic example is a typespec with a methodspec in it that you want to add an annotation to.
After talking with @swankjesse about it, we decided to take the approach of making builders' collection fields public and mutable with the idea that if you're manipulating those directly, we just assume you know what you're doing …
> Mutable builder list fields

- src/main/java/com/squareup/javapoet/CodeWriter.java
- src/main/java/com/squareup/javapoet/LineWrapper.java
- src/main/java/com/squareup/javapoet/MethodSpec.java
- src/test/java/com/squareup/javapoet/MethodSpecTest.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
This introduces functionality that tracks the last char emitted, and uses it to check if a trailing newline needs to be added after emitting a codeblock for javadocs and method bodies.
Resolves #731
Resolves #722
I tried to keep this as performant and lightweight as possible. If this implementation looks good, I'll do the same for KotlinPoet.
> Ensure trailing newlines in javadocs and method bodies

- src/main/java/com/squareup/javapoet/CodeWriter.java
- src/test/java/com/squareup/javapoet/CodeWriterTest.java
Use regex for new line character to cover both dos and unix endings when calling emitAndIndent - fixes #552
> Hardcoded line separator bug

- src/main/java/com/squareup/javapoet/CodeWriter.java
- src/main/java/com/squareup/javapoet/JavaFile.java
- src/main/java/com/squareup/javapoet/TypeSpec.java
- src/test/java/com/squareup/javapoet/JavaFileTest.java
- src/test/java/com/squareup/javapoet/TypeSpecTest.java
Implementation based on https://github.com/square/javapoet/issues/77#issuecomment-507387399
Resolves #77
Note that I'm not sure what to do about nested types like `java.util.Map.Entry`, open to suggestions!
CC @eamonnmcmanus
> Add alwaysQualify() API to avoid collisions with known colliding types

- src/main/java/com/squareup/javapoet/MethodSpec.java
- src/test/java/com/squareup/javapoet/MethodSpecTest.java
- Change to not copy parameter annotations was first introduced in
9505ad0e027a1f125b5352ac722ea141831fbf1c.
- Change to properly copy mirror annotations in ParameterSpec.get
was introduced in a0eadbbf0e7b70f0fbbc66043536e4328c3808fd,
breaking the behavior of MethodSpec.overriding.
- This change preserves the correct behavior of ParameterSpec.get
while also removing annotations in MethodSpec.overriding.
> Remove parameter annotations in MethodSpec.overriding

- src/main/java/com/squareup/javapoet/MethodSpec.java
- src/main/java/com/squareup/javapoet/ParameterSpec.java
- src/test/java/com/squareup/javapoet/MethodSpecTest.java
- src/test/java/com/squareup/javapoet/ParameterSpecTest.java
This further preserves the behaviour discussed in https://github.com/square/javapoet/issues/482.
Unifying it for both MethodSpec.overriding and ParameterSpec.get.
> Don't copy parameter annotations when creating a ParameterSpec.

- src/main/java/com/squareup/javapoet/ParameterSpec.java
- src/test/java/com/squareup/javapoet/ParameterSpecTest.java
Annotated "this" arguments for instance methods and non-static nested
class constructors were added in Java 8. This special cases "this" and
"OuterClass.this" so that they are allowed as parameter names.
Closes #787
> Add support for explicit receiver parameters

- src/main/java/com/squareup/javapoet/CodeWriter.java
For some very large Dagger components, this can save .5s-1s per compilation.
> Precompile the pattern used for splitting at possible line-breaks

- src/main/java/com/squareup/javapoet/AnnotationSpec.java
I have "value" throughout my code in AnnotationSpecBuilders and it would be nice to replace them with a AnnotationSpec.Value
> Add value constant in AnnotationSpec

- .github/workflows/build.yml
Running a build on different JDKs is pointless. Our users consume the artifact in binary form. We may want to run the tests on multiple JDKs. The way to do that is to migrate to Gradle, duplicate the test task, and use the toolchain feature. That is out of scope of this change, which is only to stop pointless CI builds.
> Only build on Java 8

- src/main/java/com/squareup/javapoet/TypeName.java
- src/test/java/com/squareup/javapoet/TypeNameTest.java
TypeName#box currently relies on identity comparisons between `this` and one of the primitive TypeName constants. However, it is possible to have an instance of a primitive that isn't any of those constants by calling TypeName#annotated or TypeName#withoutAnnotations. The returned TypeName instance can no longer be boxed.
TypeName#unbox and TypeName#isBoxedPrimitive have a similar issue. `this` is compared using `equals` instead of identity, but annotations are part of the compared string, so a boxed primitive with annotations is not found to be any of the existing constants. Annotated boxed TypeName instances can no longer be unboxed.
This PR changes behavior of all 3 methods to do a more appropriate comparison when trying to find the (un)boxed version of `this`. After (un)boxing, the …
> Fix boxing and unboxing of annotated primitives

- src/main/java/com/squareup/javapoet/AnnotationSpec.java
- src/test/java/com/squareup/javapoet/AnnotationSpecTest.java
> Add L to long values to prevent them from being interpreted as int
